// ace-copilot-core: Agent loop, task planner, tool system, LLM client abstractions, agent teams

// Generate version.properties from gradle.properties at build time
tasks.register("generateVersionProperties") {
    val outputDir = layout.buildDirectory.dir("generated/resources/version")
    inputs.property("version", project.version)
    inputs.property("group", project.group.toString())
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile
        dir.mkdirs()
        dir.resolve("version.properties").writeText(
            "# Generated by build\nversion=${project.version}\ngroup=${project.group}\n"
        )
    }
}

sourceSets["main"].resources.srcDir(layout.buildDirectory.dir("generated/resources/version"))
tasks.named("processResources") { dependsOn("generateVersionProperties") }

dependencies {
    api(project(":ace-copilot-sdk"))
    implementation(project(":ace-copilot-infra"))

    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    implementation("org.slf4j:slf4j-api")
}
